### ISSUE TITLE
豆瓣已经全站https

### ISSUE THREAD

**Issue by hntee** [JiajunW/douban2readfree#1]
请更新一下脚本...

**Comment by Ovilia** [comment]
上个月已经修复了

**Comment by Ovilia** [comment]
@hntee 这个 ff 已经没人维护了……尽量使用 Chrome 版本吧

**Comment by hntee** [comment]
@Ovilia 用的是greasemonkey的版本

**Comment by JiajunW** [comment]
@hntee Thanks, I will fix it tonight

**Comment by Ovilia** [comment]
参考：https://github.com/Ovilia/readfree-chrome-extension/commit/d5d456e3b173566cfc808d66cd6798cb22a579eb

**Comment by JiajunW** [comment]
Fixed in b7ce7b7.
