### ISSUE TITLE
测试用不了

### ISSUE THREAD

**Issue by xtay573269555** [JiajunW/douban2readfree#2]
我用项目示例截图中的"十二楼"测试，用不了，显示不了ReadFree的图标，是豆瓣那边的数据格式有改动吗？

**Comment by JiajunW** [comment]
是因为 readfree 上没这本书。

目测你看的是这本 https://book.douban.com/subject/2267558/ 而例子里是这本 https://book.douban.com/subject/1954594/

**Comment by xtay573269555** [comment]
我的结果正好和你相反。。。
https://book.douban.com/subject/2267558/ 这个能显示出ReadFree，https://book.douban.com/subject/1954594/ 显示不了ReadFree。是打字打错了吗？

我的截图如下：
![book_2267558](https://user-images.githubusercontent.com/5844466/26878730-1aac8af4-4bc1-11e7-8110-5bd9949afaa7.png)
![book_1954594](https://user-images.githubusercontent.com/5844466/26878740-23715e80-4bc1-11e7-8ec5-9bd42d0e8c5c.png)
![addons](https://user-images.githubusercontent.com/5844466/26878743-29fc0174-4bc1-11e7-861b-319146b0b43f.png)
![userscripts](https://user-images.githubusercontent.com/5844466/26878758-302bec4e-4bc1-11e7-8957-fc64a91e3aef.png)

FireFox版本 45.6.0 ESR

**Comment by JiajunW** [comment]
不好意思说反了……嘛，反正就是这有一本 readfree 上面没有收录所以没有对应的链接，所以放心，脚本还是好用的~

**Comment by xtay573269555** [comment]
嗯嗯，谢谢！
