### ISSUE TITLE
图标显示比例

### ISSUE THREAD

**Issue by larry8916** [JiajunW/douban2readfree#4]
你好，请问下，这个图标显示超级大是怎么回事？
![image](https://user-images.githubusercontent.com/24448319/51529423-f3468e00-1e38-11e9-8380-689f479b115d.png)
两个浏览器均测试。

系统：win 10,
浏览器：
- Google Chrome 版本 71.0.3578.98（正式版本） （64 位）
- Firefox: 64.0.2 (64-bit)

**Comment by JiajunW** [comment]
抱歉，之前的更新里样式有点问题，已经修复了！
